# Generated by Django 4.0.4 on 2024-05-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='댓글수',
            field=models.IntegerField(default=0),
        ),
    ]
